displayName: HTTP Logger Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/fzoli/traefiklogger

summary: 'Prints each HTTP request and response with body to standard output.'

testData:
  Headers:
    Foo: Bar
