name: traefik-logger-example

services:

  traefik:
    image: traefik:3.0
    restart: always
    #labels:
    #  - "co.elastic.logs/enabled=true"
    #  - "co.elastic.logs/json.keys_under_root=true"
    #  - "co.elastic.logs/json.overwrite_keys=true"
    #  - "co.elastic.logs/json.add_error_key=true"
    #  - "co.elastic.logs/json.expand_keys=true"
    ports:
      - "127.0.0.1:8000:80"
      - "127.0.0.1:8001:8080"
    networks:
      - traefik
    #working_dir: "/" # only for plugin development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      #- ./plugins-local:/plugins-local # only for plugin development

  nginx:
    image: nginx:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/example`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nginx-logger.plugin.traefiklogger.Enabled=true"
      - "traefik.http.middlewares.nginx-logger.plugin.traefiklogger.Name=nginx"
      - "traefik.http.middlewares.nginx-logger.plugin.traefiklogger.LogFormat=text"
      #- "traefik.http.middlewares.nginx-logger.plugin.traefiklogger.LogFormat=json"
      - "traefik.http.routers.nginx.middlewares=nginx-logger@docker"
    networks:
      - traefik

networks:
  traefik:
  #external: true # on a real environment both service has separate compose file
