name: traefik-logger-example

services:

  traefik:
    image: traefik:3.0
    restart: always
    ports:
      - "127.0.0.1:8000:80"
      - "127.0.0.1:8001:8080"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml

  nginx:
    image: nginx:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/example`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nginx-logger.plugin.traefiklogger.Enabled=true"
      - "traefik.http.middlewares.nginx-logger.plugin.traefiklogger.Name=nginx"
      - "traefik.http.routers.nginx.middlewares=nginx-logger@docker"
    networks:
      - traefik

networks:
  traefik:
  #external: true # on a real environment both service has separate compose file
