entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
api:
  dashboard: true
  insecure: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
experimental:
  plugins:
    traefiklogger:
      moduleName: "github.com/fzoli/traefiklogger"
      version: "v0.7.10"
